pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh "curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash - && sudo apt-get install -y nodejs"
                sh "node -v"
                sh "sudo npm install"
                sh "sudo npm run build"
            }
        }
        stage("Deploy") {
            steps {
                sh "sudo rm -rf /home/nutz/domains/sca.nutz.page/public_html/"
                sh "sudo cp -r ${WORKSPACE}/build/ /home/nutz/domains/sca.nutz.page/public_html/"
            }
        }
    }
}